# -*- coding: utf-8 -*-
"""hello

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mIt33YJtUq7QKt-mPxiCBWqa2tRWo04U

Week2 Assignemet2 s24013273
"""

# hello.py
print("Hello, GitHub!")



import requests

# Replace <your-username> and <repository-name> with your actual GitHub username and repository
url = "https://raw.githubusercontent.com/<Diniwe97>/<Diniwe97>/main/hello.py"

response = requests.get(url)

if response.status_code == 404:
    print("Fetched Script Content:")
    print(response.text)
else:
    print(f"Failed to fetch script! HTTP Status Code: {response.status_code}")