# -*- coding: utf-8 -*-
"""hello

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19LaUyNWnMGUlG3jGguio3jmtw2giQZEd

Assignment 02 Week 2
"""

# hello.py
print("Hello, GitHub!")

pip install requests

import requests

# Replace <your-username> and <repository-name> with your actual GitHub username and repository
url = "https://raw.githubusercontent.com/<Diniwe97>/<Diniwe97>/main/hello.py"

response = requests.get(url)

if response.status_code >= 200:
    print("Fetched Script Content:")
    print(response.text)
else:
    print(f"Failed to fetch script! HTTP Status Code: {response.status_code}")