# -*- coding: utf-8 -*-
"""hello

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mIt33YJtUq7QKt-mPxiCBWqa2tRWo04U

Week2 Assignemet2 s24013273
"""

# hello.py
print("Hello, GitHub!")